# Generated by Django 5.2.1 on 2025-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssnews',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
