# Generated by Django 5.2.1 on 2025-05-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_rssnews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssnews',
            name='link',
            field=models.URLField(max_length=2000),
        ),
    ]
