# Generated by Django 5.2.1 on 2025-05-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
