# Generated by Django 5.2.1 on 2025-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnews',
            name='shared',
            field=models.IntegerField(default=0),
        ),
    ]
